//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class au_users
    {
        public au_users()
        {
            this.ppe_messages = new HashSet<ppe_messages>();
        }
    
        public int id { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public Nullable<int> ppe_id { get; set; }
        public Nullable<int> area_id { get; set; }
        public bool disable { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual au_roles au_roles { get; set; }
        public virtual ppe ppe { get; set; }
        public virtual ICollection<ppe_messages> ppe_messages { get; set; }
    }
}
