//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class blank_types
    {
        public blank_types()
        {
            this.subject_blanks = new HashSet<subject_blanks>();
            this.journals = new HashSet<journals>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int blank_kind_id { get; set; }
        public string short_name { get; set; }
        public string folder_name { get; set; }
    
        public virtual ICollection<subject_blanks> subject_blanks { get; set; }
        public virtual ICollection<journals> journals { get; set; }
    }
}
