//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_dates
    {
        public exam_dates()
        {
            this.ppe_exams = new HashSet<ppe_exams>();
        }
    
        public int id { get; set; }
        public int subject_id { get; set; }
        public System.DateTime exam_date { get; set; }
        public int wave_id { get; set; }
        public string description { get; set; }
        public int @class { get; set; }
        public bool is_actual { get; set; }
    
        public virtual subjects subjects { get; set; }
        public virtual ICollection<ppe_exams> ppe_exams { get; set; }
    }
}
