//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppe
    {
        public ppe()
        {
            this.au_users = new HashSet<au_users>();
            this.ppe_exams = new HashSet<ppe_exams>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int area_id { get; set; }
        public bool is_tom { get; set; }
        public int ppe_code { get; set; }
        public int @class { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual ICollection<au_users> au_users { get; set; }
        public virtual ICollection<ppe_exams> ppe_exams { get; set; }
    }
}
