//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppe_exam_statuses
    {
        public ppe_exam_statuses()
        {
            this.ppe_exams = new HashSet<ppe_exams>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ppe_exams> ppe_exams { get; set; }
    }
}
