//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppe_exams
    {
        public ppe_exams()
        {
            this.journals = new HashSet<journals>();
            this.ppe_messages = new HashSet<ppe_messages>();
        }
    
        public int id { get; set; }
        public int exam_date_id { get; set; }
        public int ppe_id { get; set; }
        public string files_path { get; set; }
        public Nullable<int> status_id { get; set; }
        public bool is_upload_data { get; set; }
    
        public virtual exam_dates exam_dates { get; set; }
        public virtual ppe ppe { get; set; }
        public virtual ppe_exam_statuses ppe_exam_statuses { get; set; }
        public virtual ICollection<journals> journals { get; set; }
        public virtual ICollection<ppe_messages> ppe_messages { get; set; }
    }
}
