//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGEServiceRun.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppe_messages
    {
        public int id { get; set; }
        public int ppe_exam_id { get; set; }
        public int user_id { get; set; }
        public string message { get; set; }
        public System.DateTime mes_date { get; set; }
    
        public virtual au_users au_users { get; set; }
        public virtual ppe_exams ppe_exams { get; set; }
    }
}
